### PR TITLE
Minor logging fix

### PR DESCRIPTION
**Pull request by sratcliffe**
I am also wondering if we should downgrade the sensor update INFO logging (specifically the two log lines in _update_sensor). This is being triggered quite regularly by the data_suspect sensors now and is a little polluting....

### CODE REVIEW

**Review by bmerry — APPROVED** [review]
Good catch. Was this found because it triggered in production? If so that's a little worrying, implying that there is something non-causal in the system.

I don't mind if you want to downgrade some of the other logging if you're happy that it's all working properly. It was pretty useful to have those log messages when I was debugging the incorrect applicable of sensors.

**Comment by sratcliffe** [comment]
It does seem to have been triggered quite regularly (perhaps with the advent of data_suspect). Here is a recent example: http://ing1.sdp.mkat.karoo.kat.ac.za:5051/files/download?path=%2Fvar%2Flib%2Fmesos%2Fslaves%2F57db2fe2-4fe6-4b5a-a431-a34d2f67a9e6-S71%2Fframeworks%2F183d5e14-1ce9-409c-a1a0-43787f9bd9b2-0725%2Fexecutors%2Farray_1_wide_0-00000010%2Fruns%2Fff49af93-4de6-44a8-ad54-f837c2e21e72%2Fstderr

As for the sensor logging, it is almost worth special casing the data_suspect sensors and not logging them, since the others only really happen at the start and are quite useful, but it feels more clunky than it is worth...

**Comment by bmerry** [comment]
I see in the log messages the two timestamps are the same (at least to µs precision). It could be something causing telstate to report the same sample twice. We should probably only report the error if the new timestamp is strictly before the old.

**Comment by sratcliffe** [comment]
Indeed - I see that elsewhere in the code the checks are all strictly less than. Shall we just update the check, and thus add updates with the same timestamp, or do you want to have a third case for handling updates with the same timestamp (maybe discard them) ?

**Comment by bmerry** [comment]
I'd rather have a third case and discard updates with the same timestamp, because I'm not confident that the rest of the code will do the right thing with duplicates.

**Comment by bmerry** [comment]
Since you say this happens frequently, maybe we should only log it at INFO level? (or even DEBUG)?

**Comment by sratcliffe** [comment]
Since we shouldn't have duplicates, my thinking was to have it as a WARN for a bit to see how often it is happening and why, and then downgrade to DEBUG once we understand it.

**Comment by bmerry** [comment]
Ok

**Review by bmerry — APPROVED** [review]

**Pull request merged**
